name: "Copy local file and publish to Maven repo"
description: "This GitHub Action copies a file using a local path and publishes it to a Maven repository"
inputs:
  artifact_repo:
    description: "GitHub repository to publish artifacts"
    required: true
  gh_pat:
    description: "Personal Access Token for GitHub Maven artifact repository"
    required: true
  artifact_path:
    description: "Local file path"
    required: true
  artifact_source_path:
    description: "Local source file path"
    required: false
    default: ""
  artifact_id:
    description: "Artifact ID"
    required: true
  group_id:
    description: "Group ID"
    required: true
  version:
    description: "Version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet
      shell: bash

    - name: Set environment variables
      run: |
        echo "GROUPID_PATH=$(echo '${{ inputs.group_id }}' | tr '.' '/')" >> $GITHUB_ENV
        ORIGINAL_FILENAME=$(basename ${{ inputs.artifact_path }})
        EXTENSION="${ORIGINAL_FILENAME##*.}"
        echo "EXTENSION=$EXTENSION" >> $GITHUB_ENV
      shell: bash

    - name: Checkout artifact repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.artifact_repo }}
        token: ${{ inputs.gh_pat }}
        path: src

    - name: Create package directories
      run: mkdir -p src/${{ env.GROUPID_PATH }}/${{ inputs.artifact_id }}/${{ inputs.version }}
      shell: bash

    - name: Copy artifact
      run: |
        cp ${{ inputs.artifact_path }} src/${{ env.GROUPID_PATH }}/${{ inputs.artifact_id }}/${{ inputs.version }}/${{ inputs.artifact_id }}-${{ inputs.version }}.${{ env.EXTENSION }}
      shell: bash

    - name: Copy source artifact if provided
      if: inputs.artifact_source_path != ''
      run: |
        ORIGINAL_SOURCE_FILENAME=$(basename ${{ inputs.artifact_source_path }})
        SOURCE_EXTENSION="${ORIGINAL_SOURCE_FILENAME##*.}"
        echo "SOURCE_EXTENSION=$SOURCE_EXTENSION" >> $GITHUB_ENV
        cp ${{ inputs.artifact_source_path }} src/${{ env.GROUPID_PATH }}/${{ inputs.artifact_id }}/${{ inputs.version }}/${{ inputs.artifact_id }}-${{ inputs.version }}-sources.${SOURCE_EXTENSION}
      shell: bash

    - name: Generate Metadata
      run: |
        TIMESTAMP=$(date +"%Y%m%d%H%M%S")
        cat <<EOF > "src/${{ env.GROUPID_PATH }}/${{ inputs.artifact_id }}/maven-metadata.xml"
        <metadata>
          <groupId>${{ inputs.group_id }}</groupId>
          <artifactId>${{ inputs.artifact_id }}</artifactId>
          <versioning>
            <latest>${{ inputs.version }}</latest>
            <release>${{ inputs.version }}</release>
            <versions>
              <version>${{ inputs.version }}</version>
            </versions>
            <lastUpdated>${TIMESTAMP}</lastUpdated>
          </versioning>
        </metadata>
        EOF
      shell: bash

    - name: Generate POM file
      run: |
        cat <<EOF > src/${{ env.GROUPID_PATH }}/${{ inputs.artifact_id }}/${{ inputs.version }}/${{ inputs.artifact_id }}-${{ inputs.version }}.pom
        <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
          <modelVersion>4.0.0</modelVersion>
          <groupId>${{ inputs.group_id }}</groupId>
          <artifactId>${{ inputs.artifact_id }}</artifactId>
          <version>${{ inputs.version }}</version>
        </project>
        EOF
      shell: bash

    - name: Extract artifactId, groupId, version from generated POM file
      run: |
        xml_file=src/${{ env.GROUPID_PATH }}/${{ inputs.artifact_id }}/${{ inputs.version }}/${{ inputs.artifact_id }}-${{ inputs.version }}.pom
        VERSION=$(xmlstarlet sel -N xmlns="http://maven.apache.org/POM/4.0.0" -t -v "//xmlns:project/xmlns:version" "$xml_file")
        GROUPID=$(xmlstarlet sel -N xmlns="http://maven.apache.org/POM/4.0.0" -t -v "//xmlns:project/xmlns:groupId" "$xml_file" | sed 's/\./\//g')
        ARTIFACTID=$(xmlstarlet sel -N xmlns="http://maven.apache.org/POM/4.0.0" -t -v "//xmlns:project/xmlns:artifactId" "$xml_file")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "GROUPID=$GROUPID" >> $GITHUB_ENV
        echo "ARTIFACTID=$ARTIFACTID" >> $GITHUB_ENV
      shell: bash

    - name: Generate checksums
      run: |
        ARTIFACT_PATH=src/${{ env.GROUPID_PATH }}/${{ inputs.artifact_id }}/${{ inputs.version }}/${{ inputs.artifact_id }}-${{ inputs.version }}
        
        # Generate checksums for the artifact and POM
        sha1sum "$ARTIFACT_PATH.${{ env.EXTENSION }}" > "$ARTIFACT_PATH.${{ env.EXTENSION }}.sha1"
        md5sum "$ARTIFACT_PATH.${{ env.EXTENSION }}" > "$ARTIFACT_PATH.${{ env.EXTENSION }}.md5"
        sha1sum "$ARTIFACT_PATH.pom" > "$ARTIFACT_PATH.pom.sha1"
        md5sum "$ARTIFACT_PATH.pom" > "$ARTIFACT_PATH.pom.md5"

      shell: bash

    - name: Generate source checksums
      if: inputs.artifact_source_path != ''
      run: |
        ARTIFACT_PATH=src/${{ env.GROUPID_PATH }}/${{ inputs.artifact_id }}/${{ inputs.version }}/${{ inputs.artifact_id }}-${{ inputs.version }}
        
        # Generate checksums for the source artifact if provided
        sha1sum "$ARTIFACT_PATH-sources.${{ env.SOURCE_EXTENSION }}" > "$ARTIFACT_PATH-sources.${{ env.SOURCE_EXTENSION }}.sha1"
        md5sum "$ARTIFACT_PATH-sources.${{ env.SOURCE_EXTENSION }}" > "$ARTIFACT_PATH-sources.${{ env.SOURCE_EXTENSION }}.md5"
      shell: bash

    - name: Commit files
      run: |
        cd src
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Added artifacts for ${{ env.ARTIFACTID }} version ${{ env.VERSION }}"
      shell: bash

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.gh_pat }}
        repository: ${{ inputs.artifact_repo }}
        directory: src
        force_with_lease: true
